In [2]:
import numpy as np
import statistics

In [45]:
def euclidean_dist(data1, data2):
  return np.sqrt(np.sum(data1 - data2)**2)

class KNeighborsClassifier:
  def __init__(self, k = 3):
    self.k = k

  def fit(self, X, Y):
    self.X_train = X
    self.Y_train = Y

  def get_class_prediction(self, x):
    distance = [euclidean_dist(X, x) for X in self.X_train]

    k_indices = np.argsort(distance)[:self.k]
    k_classes = [self.Y_train[i] for i in k_indices]

    prediction = statistics.mode(k_classes)
    return prediction

  def predict(self, X_test):
    predicted_classes = [self.get_class_prediction(x) for x in X_test]
    return predicted_classes

In [22]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [16]:
iris = datasets.load_iris()
X, Y = iris.data, iris.target

In [17]:
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [18]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1234)

In [42]:
clf = KNeighborsClassifier(k = 5)
clf.fit(X_train, Y_train)

In [43]:
Y_pred = clf.predict(X_test)

In [44]:
print('Accuracy Score - ', accuracy_score(Y_test, Y_pred))

Accuracy Score -  0.9666666666666667
